name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: create build directory
      run: mkdir build
    - name: configure
      run: cmake .. -DRUN_TESTS=ON
      working-directory: ./build
    - name: build
      run: make
      working-directory: ./build
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

  test:
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build
        path: build
    
